### ISSUE TITLE
Is it possible to remove setting "User Header Search Paths" manually?

### ISSUE THREAD

**Issue by peterprokop** [corymsmith/react-native-icons#15]
It's very inconvenient if your project uses any kind of CI system (Travis or any other)

**Comment by romanonthego** [comment]
it's actually will brake the build.
since project kept in npm modules he will probably will be under gitignore and will not keep search path config through commits.
i've solve it by forking the repo, setting User Header Search Paths and reference my fork as source in package.json.

is there any reason to not set this config by default?

**Comment by corymsmith** [comment]
I just set this by default, thanks for the suggestion @romanonthego & @peterprokop
