### ISSUE TITLE
Suggestion of breaking this project into 2 projects

### ISSUE THREAD

**Issue by alinz** [corymsmith/react-native-icons#82]
Hi,
I was thinking if it possible to break this project into 2 different projects. One for Icons and another for Tabs.

**Comment by jdmunro** [comment]
Not a bad suggestion. Actually, at first I was surprised that there was a full blown tab bar implementation within this library. Having said that, it is convenient to have it there although I can see why that will not be appropriate for everybody's requirements.

**Comment by alinz** [comment]
@corymsmith are you agree with this suggestion? if so can you create another project so I can give you the PR?

**Comment by corymsmith** [comment]
I don't really agree with this, the entire reason for doing the tab bar implementation was so that you could easily use the icons in the tab bar. Doesn't hurt anything to keep it in this project and would be more work to maintain 2 projects and they need a lot of shared code. Also lots of people use the tab bar implementation so it would be a breaking change.

**Comment by alinz** [comment]
Fair enough. Thanks for the reply!

**Comment by corymsmith** [comment]
No worries! On vacation in Australia so my replies were a bit delayed :)
